# JUnit Platform configuration for Cucumber
# Author: Nitheesh
cucumber.junit-platform.naming-strategy=long
cucumber.publish.quiet=true
cucumber.plugin=pretty,\
  json:target/cucumber-reports/cucumber.json,\
  html:target/cucumber-reports/cucumber.html,\
  io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm
cucumber.glue=stepdefs
cucumber.features=src/test/resources/features
